### ISSUE TITLE
HTTP 422 when creating listener with insert_header

### ISSUE THREAD

**Issue by laerlingSAP** [sapcc/octavia-f5-provider-driver#51] opened 2020-02-27 16:06 UTC
F5 is responding with [HTTP status 422](https://httpstatuses.com/422) when trying to create listener with `insert_header` via Octavia API.

Steps to reproduce:
1. Create load balancer via Octavia API
2. Create listener on load balancer with `insert_header` field set, e.&nbsp;g.:
```
{
    "listener": {
        "loadbalancer_id": "a67bf7f7-4750-4ca3-9544-ae74cfeefbec",
        "protocol": "HTTP",
        "protocol_port": "1234",
        "insert_headers": {
        	"X-Forwarded-For": "true"
        }
    }
}
```

Observations:
- Octavia responds with an error if the boolean literal is unquoted (`true` instead of `"true"`), even though unquoted booleans are idiomatic JSON. In this case the provider driver does not receive anything.
- After creating the listener with the above JSON, the database table `listener` has the following content in its column `insert_header`: `<80>^D<95>^]       }<94><8C>^OX-Forwarded-For<94><8C>^Dtrue<94>s.` (escape sequences are an artifact of displaying the output in less)
- The F5 responds with [HTTP status 422](https://httpstatuses.com/422) (supported media type, good request, but unable to process semantically)

If Octavia not accepting `true` is the cause of all this, I fear we'll have to file an issue upstream...

**Comment by laerlingSAP** [comment] 2020-02-27 16:37
I deleted all objects on F5, set `dry_run` in my Octavia configuration file and tried to reproduce: No success.

Again deleted all objects on F5, set `dry_run` to false and tried to reproduce: No success.


I guess it was some sort of weird constellation of objects on the F5 that resulted in HTTP 422.

**Comment by laerlingSAP** [comment] 2020-02-27 16:39
Removing milestone 'Rollout', but keeping issue open for now.

**Comment by notandy** [comment] 2020-03-30 12:17
closing since not reproducable, you can still reopen if you encounter again

**Closed by notandy** 2020-03-30 12:17 UTC
Labels: bug
